### ISSUE TITLE
Unexpected Token 

### ISSUE THREAD

**Issue by jeffrobernard** [caseyyee/unity-webvr-export#13]
Hello, 
I've tried in vain to get your Git working to export from Unity, but I keep getting the error below. Any ideas on what may be the problem. Thanks for working on this in general. I've been trying to find a functioning WebVr export for months now. 
Assets/unity-webvr-export-master/Assets/WebGLTemplates/WebVR/webvr.js(11,19): BCE0043: Unexpected token: ,.

**Comment by caseyyee** [comment]
@jeffrobernard What browser & headset are you using?

**Comment by jeffrobernard** [comment]
Firefox Nightly. The problem is that the project won’t play in unity player. I was going to use all the plumbing you put together and export and use in Nightly, but unity keeps throwing that unexpected token error. 

Kindest Regards,

Jeff Bernard

**Comment by caseyyee** [comment]
@jeffrobernard Ah, OK.  I just now realized that you were referring to playing the project in the Unity editor.   That won't work right now.  You'll have to build the project, then fire up a web server from the directory where the project is built to, and then load it up in Firefox Nightly to see the project in WebVR.

In later versions, the goal is to make this workflow better by enabling a VR view in the editor:
https://github.com/caseyyee/unity-webvr-export/issues/14

**Comment by jeffrobernard** [comment]
Oh that makes sense. Thanks for the response. 

Kindest Regards,

Jeff Bernard

**Comment by caseyyee** [comment]
Going to close this one for now and address it as part of issue #14

**Comment by caseyyee** [comment]
@jeffrobernard this work now, feel free to give it a go :)
