### ISSUE TITLE
Document supported/tested Unity Editor versions

### ISSUE THREAD

**Issue by cvan** [caseyyee/unity-webvr-export#50]
Put the info in the `README.md` file.

**Comment by caseyyee** [comment]
already in readme under setup instructions.

**Comment by cvan** [comment]
We have only `2017.2.0f3` listed. I know we've tested `2017.3.0f3` as well.

![image](https://user-images.githubusercontent.com/203725/35594121-eaeecb04-05c6-11e8-814f-f35def07e9cf.png)

Can we move the compatible Unity versions up to the **`Compatibility`** heading too?

**Comment by caseyyee** [comment]
Yeah, I think there needs to be a distinction between consuming content in the browser and using the components in Unity.  Good call.
