### ISSUE TITLE
add default Service Worker (for Chrome PWA detection)

### ISSUE THREAD

**Issue by cvan** [caseyyee/unity-webvr-export#55]
can be blank for now (or contain a comment with a link to [Workbox](https://github.com/GoogleChrome/workbox)).

to make exported games PWA-able, at the minimum, a `sw.js` file must exist and the page must call `navigator.serviceWorker.register` to register it.

we can update it to add full-blown Service Worker offline capabilities later.

**Comment by delapuente** [comment]
For the aesthetics; leave it to me.
