### ISSUE TITLE
stuck at loading screen 

### ISSUE THREAD

**Issue by miguelmyers8** [caseyyee/unity-webvr-export#62]
I am using unity 5.6. I followed the first half of the ReadMe and ended up stuck at loading screen after hitting "build and run". In addition I had to add webGLTemplates to my assets because it originally wasn't there. 

Can anyone assist with this?

**Comment by cvan** [comment]
@miguelmyers8: thanks for trying this out. can you open the Console of your Developer Tools and paste any errors/warnings (a screenshot would be fine).

@caseyyee: any ideas here? is it because of the Unity version, you think? (we've been testing with `2017.2.0f3`.)

**Comment by caseyyee** [comment]
Yeah, this won't work for 5.6.  Your best bet is to update your project to use the 2017.x versions of Unity.

**Comment by miguelmyers8** [comment]
so i upgraded to the latest version. still stuck at load screen.
![screen shot 2018-01-11 at 1 31 07 pm](https://user-images.githubusercontent.com/18605314/34840778-08b8f670-f6d4-11e7-92d9-05c56ef3482a.png)

**Comment by caseyyee** [comment]
@miguelmyers8 What browse, OS and VR setup?

**Comment by miguelmyers8** [comment]
I am using a mac with firefox and chrome. yes, the demo works very well. I have a feeling its something i am missing in my set up.

**Comment by caseyyee** [comment]
@miguelmyers8 want to give it a fresh pull and see if it works for you?  

Also, how are you using the assets?  Are you just opening the cloned folder as per the instructions in the readme?  Or are you importing as a asset into an existing project?

**Comment by mirrorspock** [comment]
I am getting the exact same issue, I have put the "WebGLTemplates" folder into my existing project, and published it.

https://mirrorspock.github.io/VRFPS/index.html

my setup is:
Unity 2017.30f3 (Mac)

and also, the readme Demo worked fine for me.

**Comment by mirrorspock** [comment]
Possible fix:
The problem was with not adding the Camera script and prefabs to the existing scene

**Comment by cvan** [comment]
@caseyyee can update the screenshots and instructions to reflect this?

**Comment by caseyyee** [comment]
Yup, this is because the instructions for using the asset bundle are not in the readme.  will do!

**Comment by caseyyee** [comment]
this issue covers this case:
https://github.com/caseyyee/unity-webvr-export/issues/19
