### ISSUE TITLE
Document input

### ISSUE THREAD

**Issue by delapuente** [caseyyee/unity-webvr-export#75]
List the mappings for the different controllers.

**Comment by caseyyee** [comment]
https://github.com/caseyyee/unity-webvr-export/issues/8

**Comment by delapuente** [comment]
I use this snippet to show the buttons pressed:

```js
navigator.getGamepads()[0].buttons.forEach((b,i) => console.log(`${i}: pressed: ${b.pressed}, touched: ${b.touched}, value: ${b.value}`))
```

**Comment by delapuente** [comment]
### VIVE controllers

Button | WebVR Unity label 
--------|-------------------
Menu | `"joystick button 3"`
Touch | `"joystick button 0"`
System | 
Trigger | `"joystick button 1"`
Grip | `"joystick button 2"`
