### ISSUE TITLE
Do not capture `space` and other keys by default.

### ISSUE THREAD

**Issue by delapuente** [caseyyee/unity-webvr-export#79]
Currently, the space key toggles between normal and vr mode but it is not documented and it can interfer with a game custom controls.

`p` and `v` keys also map to unexpected functionality. Instead we should document the API and let the developers to use it.

**Comment by caseyyee** [comment]
https://github.com/caseyyee/unity-webvr-export/issues/8

**Comment by delapuente** [comment]
Stealing this from you @cvan ;) I'll add how to recover the functionality somewhere in the Docs.
